cmake_minimum_required(VERSION 3.16)
project(PGTraceCleaner LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_BUILD_TYPE Release CACHE STRING "" FORCE)
set_property(CACHE CMAKE_BUILD_TYPE PROPERTY STRINGS Release)
set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded")
add_compile_options(/O1 /Os /Oy /Gw /GS- /GA /GL /EHsc /W3)
add_link_options(/LTCG /OPT:REF /OPT:ICF /INCREMENTAL:NO /MANIFEST:EMBED /MANIFESTUAC:level='requireAdministrator' /DYNAMICBASE /NXCOMPAT /SUBSYSTEM:CONSOLE)
add_executable(PGTraceCleaner src/main.cpp src/console.cpp src/file.cpp src/process.cpp src/registry.cpp)
target_include_directories(PGTraceCleaner PRIVATE include)
